# Model arguments
model_name_or_path: /opt/ml/input/data/model
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
use_peft: true

## peft config
lora_r: 32
lora_alpha: 128
lora_dropout: 0.1
target_modules: ["q_proj", "v_proj"]
use_liger_kernel: true

# Data training arguments
dataset_name: /opt/ml/input/data/training_data
dataset_config: default
dataset_prompt_column: problem
system_prompt: "You are a helpful AI Assistant, designed to provided well-reasoned and detailed responses. You FIRST think about the reasoning process as an internal monologue and then provide the user with the answer. The reasoning process MUST BE enclosed within <think> and </think> tags."

# GRPO trainer config
bf16: true
use_vllm: true
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: true
learning_rate: 3.0e-06
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 5
logging_strategy: steps
logging_dir: /opt/ml/output/tensorboard
lr_scheduler_type: cosine
max_prompt_length: 512
max_completion_length: 1024
max_steps: -1
num_generations: 4
num_train_epochs: 1
output_dir: /opt/ml/model
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
report_to:
- tensorboard
reward_funcs:
- accuracy
- format
reward_weights:
- 1.0
- 1.0
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
